### ISSUE TITLE
Why subtract 'frames_per_segment' to calculate 'segment_duration' ?

### ISSUE THREAD

**Issue by Gateway2745** [RaivoKoot/Video-Dataset-Loading-Pytorch#12]
Hi. Why do you subtract 'frames_per_segment' from 'num_frames' and then divide by 'num_segments' to calculate 'segment_duration' ? Can we not directly divide 'num_frames' by 'num_segments' to get the 'segment_duration' ? Thanks!

https://github.com/RaivoKoot/Video-Dataset-Loading-Pytorch/blob/97b54d804adfbf0baf8537bfe525f5d36469abd9/video_dataset.py#L155

**Comment by RaivoKoot** [comment]
Yes, you are right that this is how it works, even though it is not the best behavior. Because most people only use a single frame per segment, I did not pay much attention to improving this behavior, when I adapted this repostiroy from the original code repository, which implemented this sub-optimal behavior. In my own experiments, I also only ever use a single frame per segment.

However, you are very welcome to create a pull request and suggest an improvement for this. If it is suitable, I am happy to merge it!!

**Comment by Gateway2745** [comment]
Hi. Thanks for the confirmation! Oh I see, I was not aware that the norm was to use only a single frame per segment. Sure, although it is difficult for me right now, if I come up with a way to improve the current strategy, I'll definitely raise a PR. Thanks again.
